### ISSUE TITLE
weak factors hard to see in plotVarianceExplained()

### ISSUE THREAD

**Issue by frederikziebell** [bioFAM/MOFA2#30]
Hi Ricard et al.,
I noted that it's often hard to see for weak factors whether they are shared between omics and that you introduced `min_r2` and `max_r2` for filtering the plot. Another solution would be to set `scale_fill_gradientn(trans='sqrt')` and maybe add a switch like `transform_scale=TRUE/FALSE` .
Example untransformed: 
![Bildschirmfoto 2019-11-12 um 10 49 36](https://user-images.githubusercontent.com/28304028/68661022-88d31b80-053a-11ea-9d67-f1cb737cd55b.png)
Example transformed:
![Bildschirmfoto 2019-11-12 um 10 49 43](https://user-images.githubusercontent.com/28304028/68661033-94264700-053a-11ea-92e1-a045dea6e78a.png)

**Comment by gtca** [comment]
Hello Frederik,

Thanks for your feedback for the variance explained plots.

You are right there are arguments `min_r2` and particularly `max_r2` that could help to make a sharper variance explained plot. The latter parameter might be particularly useful regarding your question since e.g. `max_r2 = 0.2` would mark all the tiles with R2 of 0.2 and higher as the darkest ones.
And one can also select less factors for this plot with `factors=...`, which might also help.

At the moment you can add the gradient scale that you suggested to the existing `plot_variance_explained` call:

```r
plot_variance_explained(model) + 
  scale_fill_gradient(trans = 'sqrt', high = "black", low = "white")
```

This way other transformed scales as well as other ggplot2 features can be combined with the `plot_variance_explained` call.
Do you think that would work for your case?

**Comment by frederikziebell** [comment]
Hi Danila,

I didn't think of this particular solution. Still I think the default variance explained plot could be improved. The main question I want to answer with this plot are 
1) How strong is each factor?
2) How active is each factor in each view?

While the linear color-scale answers the first question, it does not always give good results for the second one. How about having a second bar-chart on the side summing-up the individual tiles for each factor and a non-linear color scale? This way you can answer both questions in one plot.

**Comment by gtca** [comment]
Getting back to this discussion, there's a new `summarise_factors()` functionality that might help you to address some of your questions.

We probably don't want to complicate `plot_variance_explained()` code more at this point but we're happy to review pull requests with improvements!
And simple extensions of the existing plot like a non-linear colour scale can be easily added with ggplot2-compatible functions like `scale_fill_gradient`.
