### ISSUE TITLE
Documentation of get_default_data_options() incomplete.

### ISSUE THREAD

**Issue by frederikziebell** [bioFAM/MOFA2#39]
The function `get_default_data_options()` creates a list with 4 elements: `scale_views`, `scale_groups`, `views` and `groups`.  Only `scale_views` is explained (twice), all others are missing. In particular, it is not clear from there, how to define multiple groups.

**Comment by gtca** [comment]
There's been a typo with `scale_groups`, should be fixed in `master` now.
The function `get_default_data_options()` only returns a list of those two options — more items there are fetched from a pre-existing `data_options` slot of the object.

As described, these options are only related to scaling.

View / group definition is specified with the `create_mofa()`, see the docs and the vignettes, and feel free to open new issues if you find some more bits there confusing.
